### ISSUE TITLE
压缩包损坏了

### ISSUE THREAD

**Issue by DongRuiH** [maple0leaves/YOLOv5_D435i#2]
你好，下载的压缩包显示损坏了，可以上传一份新的吗？

**Comment by maple0leaves** [comment]
你好，看一下是不是你那边出现了什么问题，在我这可以下载压缩包并且运行

**Comment by DongRuiH** [comment]
您好，可以加您一个联系方式吗，我有一些代码问题想请教。

**Comment by DongRuiH** [comment]
>您好，我看了一下还是有一点问题，您可以邮箱发给我吗，这是我的邮箱1020272179@qq.com

**Comment by maple0leaves** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maple0leaves/YOLOv5_D435i"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月9日(星期六) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [maple0leaves/YOLOv5_D435i] 压缩包损坏了 (Issue #2)





  
***@***.***
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

YOLOv5_D435i-master.zip (148.32M, 2024年04月08日 15:54 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7f643664b6d9dcc4c1757ac44434541d4b10505d030602511e0502525219550a565c1b020407541f055c5000530650510a51535c6223666b7c287912576b220600515f490f5515465616181e0b44660f&code=3d6db4f2
